"""create table leads

Revision ID: 000b3265eb60
Revises:
Create Date: 2021-09-29 07:36:54.338217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000b3265eb60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'lead',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=False),
        sa.Column('creation_date', sa.Date(), nullable=True),
        sa.Column('last_visit', sa.Date(), nullable=True),
        sa.Column('visits', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead')
    # ### end Alembic commands ###
